### ISSUE TITLE
Add Retry Kommand capability.

### ISSUE THREAD

**Issue by alexruperez** [intelygenz/Kommander-iOS#5]
Just as we can cancel a Kommand, we want add the capability to retry them after failure.

We have to think about how it would work, a good starting point could be our [NetClient retry policy](https://github.com/intelygenz/NetClient-iOS/blob/develop/URLSession/NetURLSession.swift#L157).

**Comment by alexruperez** [comment]
Closed by @juantrias at https://github.com/intelygenz/Kommander-iOS/pull/11

**Comment by juantrias** [comment]
I have added the capability to retry after cancellation at #11, but not after failure. I think this issue should be reopened. If you agree I'll make a PR. But first we should consider some things:

I think Retry after cancellation should be triggered by the user, so in this case we should not limit the number of retries.

We can make Retry after failure behave the same way, but if we want also to retry a Kommand programmatically after failure we ave to add a retry policy block similar to NetClient. I'm not sure if having two retry policies (one in NetClient and one in Kommander) in most use cases will cause confusion and will make retry the operations twice the times expected.

An implementation detail: in the case of failure we cannot throw from Kommander a RecoverableError, because depending on the use case it will not be recoverable (i.e. invalid auth token). The app should decide if the error is recoverable or not.

**Comment by alexruperez** [comment]
@juantrias check [this](https://www.slideshare.net/elizarov/introduction-to-coroutines-kotlinconf-2017) out:
<img width="439" alt="Introduction to Coroutines @ KotlinConf 2017" src="https://user-images.githubusercontent.com/297950/34746872-181cf114-f596-11e7-9b18-a0370b19f670.png">

**Comment by IGZJoseAngelCuadrado** [comment]
I think the changes made in #14 fix Juan's comments.
